
FROM ubuntu_16_py2.7


RUN conda install -c r r-randomforest
RUN conda install -c r r-caret

RUN conda update conda 
RUN conda install -c anaconda matplotlib
RUN conda install -c anaconda pandas=0.24.2

RUN conda install python=3
RUN conda install -c bioconda -c conda-forge snakemake

